version: "3.9"
   
services:
  docker:
    image: docker
  web:
    build: .
    #command: uwsgi --plugins-dir=/usr/lib/uwsgi/plugins --ini uwsgi_settings.ini 
    command: python manage.py runserver
    ports:
      - "80:80"