version: "3.9"
   
services:
  web:
    build: .
    image: docker-django-ui-web-image
    container_name: docker-django-ui-web-container

    #command: uwsgi --plugins-dir=/usr/lib/uwsgi/plugins --ini uwsgi_settings.ini 
    command: python manage.py runserver
    ports:
      - "80:8000"
    # attach docker sock to interact with the host docker
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:rw