# Generated by Django 2.2.13 on 2021-01-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xterm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teadas1',
        ),
        migrations.RemoveField(
            model_name='docker',
            name='temp',
        ),
    ]
